version: "3.9"

services:

  fl_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  client1:
    build:
      context: ./device_1
      dockerfile: Dockerfile
    depends_on:
      - fl_server

  client2:
    build:
      context: ./device_2
      dockerfile: Dockerfile
    depends_on:
      - fl_server